# Generated by Django 3.0.4 on 2020-03-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalCases',
            fields=[
                ('country', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('total_cases', models.BigIntegerField()),
                ('new_cases', models.IntegerField(null=True)),
                ('total_deaths', models.IntegerField(null=True)),
                ('new_dealths', models.IntegerField(null=True)),
                ('total_recovered', models.IntegerField(null=True)),
                ('active_cases', models.BigIntegerField(null=True)),
                ('serious', models.IntegerField(null=True)),
                ('per_population', models.IntegerField()),
                ('updated_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'total_cases',
            },
        ),
    ]
