# Generated by Django 3.0.4 on 2020-03-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalcases',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='totalcases',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
