# Generated by Django 3.0.4 on 2020-03-27 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200322_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalcases',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='totalcases',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='totalcases',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalcases',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
