# Generated by Django 3.0.4 on 2020-03-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20200327_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalcases',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='totalcases',
            name='updated_at',
        ),
    ]
