# Generated by Django 3.0.4 on 2020-03-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20200327_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalcases',
            name='first_case',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
